#!/bin/bash
# This is a config file for `i18n.sh`
#
# Please, preserve syntax correctly:
# values must be like "targetDir:hash"
#
# ARRAY=( "countries:moo"
#        "dinosaur:roar"
#        "bird:chirp"
#        "bash:rock" )

LANGPACKS=( "lang:37abcfdea960eada188042dcf1b0e36e"
            "info:79b4e9c5f11816ce88787e8fe52bacba"
            "datetime:3a3f52fad91c2c7bbdeff72fb1bbff36"
            "countries:yZUy3gzMPN8caGpePQ7WGQ==" )
